services:
  nginx:
    restart: always
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "80:80" # http port
      - "443:443" # http port
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    restart: always
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
      restart: always
      build: ./requirements/wordpress/
      container_name: wordpress
      env_file: ./.env
      ports:
        - "9000:9000"
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
  wordpress:
    name: wordpress