services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "80:80" # http port
      - "443:443" # http port
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    image: mariadb
    environment:
      MARIADB_USER: mysql
      MARIADB_PASSWORD: passw
      MARIADB_ROOT_PASSWORD: passw
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
      image: wordpress:latest
      container_name: wordpress
      depends_on:
        - mariadb
      ports:
        - "8080:80"
        - "9000:9000"
      environment:
        WORDPRESS_DB_HOST: mariadb:3306
        WORDPRESS_DB_NAME: mysql
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: passw
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
  wordpress: