services:

  nginx:
    restart: always
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - nextcloud:/var/www/nextcloud
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    restart: always
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
      restart: always
      build: ./requirements/wordpress/
      container_name: wordpress
      env_file: ./.env
      ports:
        - "9000:9000"
      volumes:
        - nextcloud:/var/www/nextcloud
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb

  # redis:
  #   restart: always
  #   build: ./requirements/redis/
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - inception

  nextcloud:
    restart: always
    build: ./requirements/nextcloud/
    container_name: nextcloud
    ports:
      - "9001:9001"
    volumes:
      - nextcloud:/var/www/nextcloud
    networks:
      - inception

  # vsftpd:
  #   restart: always
  #   build: ./requirements/vsftpd/
  #   container_name: vsftpd
  #   ports:
  #     - "201:201"
  #   networks:
  #     - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
  wordpress:
    name: wordpress
  nextcloud:
    name: nextcloud
