services:
  nginx:
    restart: always
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443" # http port
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    restart: always
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
      restart: always
      build: ./requirements/wordpress/
      container_name: wordpress
      env_file: ./.env
      ports:
        - "9000:9000"
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb

  redis:
    restart: always
    build: ./requirements/redis/
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    name: mariadb
  wordpress:
    name: wordpress
